openapi: 3.0.0
info:
  title: Синхронизация заказов меджу 1C и b2b порталом
  description: 1C синхронизация заказов
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/Insei/1C-b2b-orders-sync/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://c6140c9e5dcd.sn.mynetname.net/maps_back/hs/b2b
  description: Dmitriy DEV
- url: https://testoff.docke.ru/DEV_test_http/hs/b2b
  description: DEV SERVER FOR B2B
tags:
- name: orders-sync
  description: Синхронизация заказов
paths:
  /orders-events/get-unprocessed:
    get:
      tags:
      - orders-sync
      summary: Получить все необработанные события заказов
      description: "Возвращает все обновления заказов, которые не были обработаны\
        \ b2b системой.\n"
      operationId: orders-events-get-unprocessed
      responses:
        "200":
          description: OK.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventsOrdersGetResponse'
        default:
          description: Server error.
  /orders-events/send-processed:
    post:
      tags:
      - orders-sync
      summary: "Отправить UUID'ы событий заказов, что были обработаны."
      description: "Отправить id событий, что были успешно обработаны.\n"
      operationId: orders-events-send-processed
      requestBody:
        description: Массив UUID'ов событий.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventsOrdersProcessedRequest'
        required: true
      responses:
        "200":
          description: OK.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NoDataResponse'
        default:
          description: Server error.
  /orders-events/process:
    post:
      tags:
      - orders-sync
      summary: Обработать новое событие заказа.
      description: |
        Обработать новое событие заказа.
      operationId: orders-events-process
      requestBody:
        description: Событие заказа.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderSnapshotEvent'
        required: true
      responses:
        "200":
          description: OK.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NoDataResponse'
        default:
          description: Server error.
components:
  schemas:
    Status:
      type: object
      properties:
        code:
          type: integer
          description: "0 - if success, other value - fail."
          example: 0
        messages:
          type: array
          items:
            type: string
    NoDataResponse:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/Status'
    ProductPrice:
      type: object
      properties:
        value:
          type: integer
          description: Цена
        type:
          type: string
          description: Вид цены 1С (UUID Ссылки)
          format: uuid
    ProductVat:
      type: object
      properties:
        rate:
          type: integer
          description: Ставка НДС
        amount:
          type: integer
          description: Сумма НДС
    Address:
      type: object
      properties:
        id:
          type: string
          description: UUID адреса доставки в 1С
          format: uuid
        address_str:
          type: string
          description: Текстовое представление адреса доставки в 1С
    Delivery:
      type: object
      properties:
        type:
          type: string
          description: Способ доставки в 1С строкой
        desiredShipDate:
          type: string
          format: date-time
        address:
          $ref: '#/components/schemas/Address'
    ProductDiscount:
      type: object
      properties:
        percentage:
          type: integer
          description: Процент скидки
        amount:
          type: integer
          description: Сумма скидки
    OrderProduct:
      type: object
      properties:
        id:
          type: integer
          description: Идентификатор строки
        status:
          type: string
          description: Статус заказа 1С
        nomenclature:
          type: string
          description: Уникальный идентификатор номенклатуры
          format: uuid
        stock:
          type: string
          description: Уникальный идентификатор склада
          format: uuid
        shippingDate:
          type: string
          description: Дата отправки
          format: date-time
        quantity:
          type: integer
          description: Количество
        unit:
          type: string
          description: Единица измерения
        total:
          type: integer
          description: Сумма
        deliveryPrice:
          type: integer
          description: Стоимость доставки
        totalWithoutDelivery:
          type: integer
          description: Сумма без учёта доставки
        discarded:
          type: boolean
          description: Отменено
        vat:
          $ref: '#/components/schemas/ProductVat'
        price:
          $ref: '#/components/schemas/ProductPrice'
        discount:
          $ref: '#/components/schemas/OrderProduct_discount'
    Order:
      type: object
      properties:
        id:
          type: string
          description: UUID заказа
          format: uuid
        date:
          type: string
          description: Дата и время заказа
          format: date-time
        status:
          type: string
          description: Статус Заказа
        client:
          type: string
          description: "UUID клиента, поле Партнёр."
          format: uuid
        contractor:
          type: string
          description: UUID контрагента
          format: uuid
        agreement:
          type: string
          description: UUID соглашения
          format: uuid
        subdivision:
          type: string
          description: UUID подразделения
          format: uuid
        comment:
          type: string
          description: Комментарий
        statusB2b:
          type: string
          description: "Статус B2B, поле Б_СтатусЗаказаB2B в 1С"
        сurrency:
          type: string
          description: Валюта
          example: руб.
        contact:
          type: string
          description: UUID Контакта
          format: uuid
        manager:
          type: string
          format: uuid
        contactManager:
          type: string
          format: uuid
        agreementDate:
          type: string
          description: Дата согласования
          format: date-time
        total:
          type: integer
        delivery:
          $ref: '#/components/schemas/Delivery'
        products:
          type: array
          items:
            $ref: '#/components/schemas/OrderProduct'
    OrderSnapshotEvent:
      required:
      - date
      - id
      - order
      - type
      type: object
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          description: "Может быть \"update\", \"remove\", \"create\""
          example: update
        date:
          type: string
          format: date-time
        order:
          $ref: '#/components/schemas/Order'
    EventsOrdersProcessedRequest:
      type: array
      items:
        type: string
        format: uuid
    EventsOrdersGetResponse:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/Status'
        data:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/OrderSnapshotEvent'
    OrderProduct_discount:
      type: object
      properties:
        auto:
          $ref: '#/components/schemas/ProductDiscount'
        manual:
          $ref: '#/components/schemas/ProductDiscount'
